spring.application.name=cveradar

# Banco de dados
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Flyway
spring.flyway.encoding=UTF-8
spring.flyway.validate-on-migrate=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-migration-naming=true

#NVD
nvd.api.key=${NVD_API_KEY}